### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by user432** [sayakpaul/Supervised-Contrastive-Learning-in-TensorFlow-2#1]
Hey, Can Supervised Contrastive Loss be implemented for Semantic Segmentation where the output of the model is of the shape;
**features = [n, feat_dim, h, w]
target = [n, h, w]
target_embedding = [n, embed_dim, h, w]**
It would be very helpful if you can help. Thanks:)

**Comment by sayakpaul** [comment]
Hi. 

I won't recommend doing that. I would rather ask you to train an image classification model using the supervised contrastive learning framework. From there you would use the feature extractor of your image classifier as the backbone of your segmentation model.
