### ISSUE TITLE
How is this loss the same as the one in paper? (Temperature param)

### ISSUE THREAD

**Issue by iocuydi** [sayakpaul/Supervised-Contrastive-Learning-in-TensorFlow-2#2]
Hi, awesome work with this repo, I just had a question about the contrastive loss.

It appears that you use the loss defined here: https://www.tensorflow.org/addons/api_docs/python/tfa/losses/contrastive_loss
which at first glance seems different than the loss described in the supervised contrastive learning paper. For example, there is no temperature parameter. 
Is the constrative loss shown in the paper mathematically equivalent to tensorflow's contrastive loss, aside from the temperature param? If so is there a derivation somewhere that shows this? My math skills are a bit weak :)  

Thanks!

**Comment by sayakpaul** [comment]
Hi. Thanks for the kind words. 

Yes, the [contrastive loss utility provided by TensorFlow Add-ons](https://www.tensorflow.org/addons/api_docs/python/tfa/losses/contrastive_loss) is used in the implementation but with modifications - 

- Firstly, if you noticed we are first normalizing the vectors in the unit hyperspace and then we are taking the dot product. This essentially becomes the cosine similarity.

- Secondly, to make sure we are not taking the similarities in between the same images, we are taking the upper triangular matrix to discard that chance `square_to_vec(D)`. 

Here, we are assuming a constant tau (temperature) value (1) but it's open for the community to play around with it. 

Hope that helps.
