### ISSUE TITLE
Loss is None

### ISSUE THREAD

**Issue by mortezamg63** [sayakpaul/Supervised-Contrastive-Learning-in-TensorFlow-2#5]
Hello, I am running your code for flowers dataset on my Machine. But in the first epoch, it is printing Nan value on screen.

I haven't changed anything in your code (just copy) to see your results, but It is not clear why the loss is returning Nan.

Thank you in advance for your respond.

**Comment by sayakpaul** [comment]
Would suggest running it on Colab just to confirm if it's stemming from infrastructure.

**Comment by mortezamg63** [comment]
Thanks for your fast reply, It worked. But I am getting this error in the second execution:
permission denied to access authors/scl/supervised_contrastive_flowers_adam
I don't know why this error is raising.

**Comment by mortezamg63** [comment]
Thank you very much
